### PR TITLE
fix: Pass slices around instead of Vec's

### PR DESCRIPTION
**Pull request by Uzaaft**

### CODE REVIEW

**Comment by Uzaaft** [comment]
This had a minor perf increase for the full backtest locally, ranging from 1-2%. Screenshot below.
image

**Comment by calumrussell** [comment]
Nice! Appreciate your time and effort. I will have to look out for this in future because it clearly makes a big difference (and slice usage is more idiomatic I believe).

**Comment by Uzaaft** [comment]
> Nice! Appreciate your time and effort. I will have to look out for this in future because it clearly makes a big difference (and slice usage is more idiomatic I believe).

Yeah, seems like that.
I found your usage of returning `&Vec<T>` confusing. If you want to return a reference, I'd use `&[T]`, but that causes alot of breaking changes, especially with data held by the structs and lifetimes

**Comment by calumrussell** [comment]
> > Nice! Appreciate your time and effort. I will have to look out for this in future because it clearly makes a big difference (and slice usage is more idiomatic I believe).
> 
> Yeah, seems like that. I found your usage of returning `&Vec<T>` confusing. If you want to return a reference, I'd use `&[T]`, but that causes alot of breaking changes, especially with data held by the structs and lifetimes

I can see the sections you are referring to. Yes, it seems like the `DataSource` trait could have perf implications, and that would be called multiple times in the main loop. I don't think I am hitting this but I will see what the implications of changing that would be because it isn't ideal.

I am still trying to improve my Rust so appreciate the further explanation.

**Comment by Uzaaft** [comment]
We could perhaps use the key takeways from this video? 
https://www.youtube.com/watch?v=A4cKi7PTJSs

**Pull request merged**
