### PR TITLE
feat(clock): Add method to get length of clock

### PR DESCRIPTION
**Pull request by Uzaaft**
Should enable pre-allocation of hashmaps on creations, allowing speedups all across the board.
Benchmark had a small perf increase.

### CODE REVIEW

**Comment by calumrussell** [comment]
Looks good. 

This pattern is probably the most common scenario - iterating over a known set of dates - so I will add documentation for this as well.

**Comment by Uzaaft** [comment]
> Looks good.
> 
> This pattern is probably the most common scenario - iterating over a set of dates known at start of backtest - so I will add documentation for this as well.

Agreed. 
Btw, I took a look at the benchs. While they're a good starting point imo, perhaps adding two pairs of examples: One for currencies, one for stocks, would be a great starting point for users?

**Comment by calumrussell** [comment]
> > Looks good.
> > This pattern is probably the most common scenario - iterating over a set of dates known at start of backtest - so I will add documentation for this as well.
> 
> Agreed. Btw, I took a look at the benchs. While they're a good starting point imo, perhaps adding two pairs of examples: One for currencies, one for stocks, would be a great starting point for users?

I am not sure what the difference would be in terms of performance for different asset classes as the underlying data structures/implementation would be the same for each asset? 

The reason for doing crypto/random data for the other tests was data access. Having tests for other asset classes would be good but building something out further (i.e. adding a Binance API that works with `DataSource`) would take more time, and isn't a priority atm for me. The options for free data aren't great either outside of crypto.

**Comment by Uzaaft** [comment]
> > > Looks good.
> > > This pattern is probably the most common scenario - iterating over a set of dates known at start of backtest - so I will add documentation for this as well.
> > 
> > 
> > Agreed. Btw, I took a look at the benchs. While they're a good starting point imo, perhaps adding two pairs of examples: One for currencies, one for stocks, would be a great starting point for users?
> 
> I am not sure what the difference would be in terms of performance for different asset classes as the underlying data structures/implementation would be the same for each asset?
> 
> The reason for doing crypto/random data for the other tests was data access. Having tests for other asset classes would be good but building something out further (i.e. adding a Binance API that works with `DataSource`) would take more time, and isn't a priority atm for me. The options for free data aren't great either outside of crypto.

Wouldn't a yahoo finance downloaded csv of a stock be sufficient data? My reason for asking is that I don't touch crypto, so I'd rather use alator for stocks instead.

**Comment by calumrussell** [comment]
> > > > Looks good.
> > > > This pattern is probably the most common scenario - iterating over a set of dates known at start of backtest - so I will add documentation for this as well.
> > > 
> > > 
> > > Agreed. Btw, I took a look at the benchs. While they're a good starting point imo, perhaps adding two pairs of examples: One for currencies, one for stocks, would be a great starting point for users?
> > 
> > 
> > I am not sure what the difference would be in terms of performance for different asset classes as the underlying data structures/implementation would be the same for each asset?
> > The reason for doing crypto/random data for the other tests was data access. Having tests for other asset classes would be good but building something out further (i.e. adding a Binance API that works with `DataSource`) would take more time, and isn't a priority atm for me. The options for free data aren't great either outside of crypto.
> 
> Wouldn't a yahoo finance downloaded csv of a stock be sufficient data? My reason for asking is that I don't touch crypto, so I'd rather use alator for stocks instead.

Yep, same. I am using EODHD data for the downstream applications. Iirc, someone asked me for a crypto example so I just added one.

Yes, that would be fine for a test/example case. But adding something like a Yahoo Finance API adapter (that pulled data from the API and turned it into a `DataSource`) would probably need to be in another root-level package. 

I am not opposed to thisin principle, and will need to do one for EODHD at some point, but data integrations aren't a priority for me right now.

**Pull request merged**
